-- BANQUE VAN HORN — AGENDA PARTAGÉ
-- Ce script ajoute un registre de rendez-vous relié aux clients.
-- Il ne supprime ni ne modifie les prêts, clients, documents ou notes existants.

CREATE TABLE IF NOT EXISTS public.pret_agenda_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT REFERENCES public.pret_clients(id) ON DELETE SET NULL,
  client_prenom TEXT NOT NULL DEFAULT '',
  client_nom TEXT NOT NULL DEFAULT '',
  client_telegram TEXT,
  appointment_date DATE NOT NULL,
  start_time TEXT NOT NULL,
  end_date DATE NOT NULL,
  end_time TEXT NOT NULL,
  appointment_type TEXT NOT NULL DEFAULT 'autre',
  title TEXT NOT NULL DEFAULT '',
  location TEXT,
  notes TEXT,
  status TEXT NOT NULL DEFAULT 'prevu',
  responsable_username TEXT,
  created_by_username TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT pret_agenda_events_start_time_format
    CHECK (start_time ~ '^(?:[01][0-9]|2[0-3]):(?:00|30)$'),
  CONSTRAINT pret_agenda_events_end_time_format
    CHECK (end_time ~ '^(?:[01][0-9]|2[0-3]):(?:00|30)$'),
  CONSTRAINT pret_agenda_events_status_check
    CHECK (status IN ('prevu','confirme','termine','annule')),
  CONSTRAINT pret_agenda_events_type_check
    CHECK (appointment_type IN ('etude_pret','signature','remboursement','immobilier','consultation','autre')),
  CONSTRAINT pret_agenda_events_end_after_start
    CHECK (
      end_date > appointment_date
      OR (end_date = appointment_date AND end_time > start_time)
    )
);

CREATE INDEX IF NOT EXISTS pret_agenda_events_client_id_idx
  ON public.pret_agenda_events(client_id);

CREATE INDEX IF NOT EXISTS pret_agenda_events_date_range_idx
  ON public.pret_agenda_events(appointment_date, end_date);

ALTER TABLE public.pret_agenda_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Deny anonymous access to agenda events" ON public.pret_agenda_events;
CREATE POLICY "Deny anonymous access to agenda events"
  ON public.pret_agenda_events
  FOR ALL
  TO anon
  USING (false)
  WITH CHECK (false);
