-- Banque Van Horn V5 - base propre compatible avec pret_clients.id BIGINT/int8
-- À exécuter dans Supabase SQL Editor sur le projet Banque Van Horne.

create extension if not exists pgcrypto;

-- Prêts : client_id doit être compatible avec pret_clients.id = BIGINT.
do $$
begin
  if exists (select 1 from information_schema.tables where table_schema='public' and table_name='pret_loans') then
    alter table public.pret_loans drop constraint if exists pret_loans_client_id_fkey;
    alter table public.pret_loans drop column if exists client_id;
    alter table public.pret_loans add column client_id bigint references public.pret_clients(id) on delete set null;
  end if;
end $$;

update public.pret_loans l
set client_id = c.id
from public.pret_clients c
where l.client_id is null
  and lower(coalesce(l.nom,'')) = lower(coalesce(c.nom,''))
  and lower(coalesce(l.prenom,'')) = lower(coalesce(c.prenom,''));

create index if not exists idx_pret_loans_client_id on public.pret_loans(client_id);

-- Documents clients : fichier Supabase Storage OU lien externe.
drop table if exists public.pret_client_documents;
create table public.pret_client_documents (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.pret_clients(id) on delete cascade,
  doc_type text not null default 'document',
  filename text not null,
  storage_path text,
  external_url text,
  mime_type text,
  size_bytes bigint,
  uploaded_by_username text,
  created_at timestamptz not null default now(),
  constraint pret_client_documents_has_source check (storage_path is not null or external_url is not null)
);
create index if not exists idx_pret_client_documents_client_id on public.pret_client_documents(client_id);
create index if not exists idx_pret_client_documents_created_at on public.pret_client_documents(created_at desc);

-- Notes internes client.
drop table if exists public.pret_client_notes;
create table public.pret_client_notes (
  id bigint generated by default as identity primary key,
  client_id bigint not null references public.pret_clients(id) on delete cascade,
  note text not null,
  created_by_username text,
  created_at timestamptz not null default now(),
  updated_at timestamptz
);
create index if not exists idx_pret_client_notes_client_id on public.pret_client_notes(client_id);
create index if not exists idx_pret_client_notes_created_at on public.pret_client_notes(created_at desc);

-- Crédits hippiques.
create table if not exists public.pret_horse_credits (
  id bigint generated by default as identity primary key,
  dossier_id text unique,
  client_id bigint references public.pret_clients(id) on delete set null,
  client_nom text,
  client_prenom text,
  telegram text not null,
  adresse text,
  profession text,
  date_du_jour text,
  identite_presentee boolean not null default false,
  photographie_ajoutee boolean not null default false,
  piece_identite_url text,
  photographie_url text,
  coupons_count integer not null default 1,
  montant_total numeric not null default 25,
  taux numeric not null default 0,
  date_course text,
  cheval_ecurie text,
  type_pari text,
  type_pari_autre text,
  bookmaker text,
  numeros_coupons jsonb not null default '[]'::jsonb,
  coupons_enregistres boolean not null default false,
  numeros_verifies boolean not null default false,
  revenus_mensuels text,
  patrimoine text,
  garanties text,
  recommande boolean not null default false,
  referent text,
  recommandations text,
  acceptations jsonb not null default '{}'::jsonb,
  discord_text text,
  statut text not null default 'en_cours',
  created_by_username text,
  created_at timestamptz not null default now()
);
create index if not exists idx_pret_horse_credits_created_at on public.pret_horse_credits(created_at desc);
create index if not exists idx_pret_horse_credits_client_id on public.pret_horse_credits(client_id);

-- Bucket privé pour les archives clients.
insert into storage.buckets (id, name, public)
values ('client-documents', 'client-documents', false)
on conflict (id) do nothing;

-- RLS : accès navigateur bloqué, accès via API Vercel service key.
alter table public.pret_client_documents enable row level security;
alter table public.pret_client_notes enable row level security;
alter table public.pret_horse_credits enable row level security;

drop policy if exists "deny anon pret_client_documents" on public.pret_client_documents;
drop policy if exists "deny anon pret_client_notes" on public.pret_client_notes;
drop policy if exists "deny anon pret_horse_credits" on public.pret_horse_credits;

create policy "deny anon pret_client_documents" on public.pret_client_documents for all using (false) with check (false);
create policy "deny anon pret_client_notes" on public.pret_client_notes for all using (false) with check (false);
create policy "deny anon pret_horse_credits" on public.pret_horse_credits for all using (false) with check (false);

notify pgrst, 'reload schema';
