-- Banque Van Horn — dossiers clients complets et demandes de crédit
-- Migration additive : elle ne supprime ni les clients ni les prêts existants.
-- À exécuter une seule fois dans Supabase > SQL Editor > New query.

-- 1) Informations complémentaires sur les clients.
alter table public.pret_clients add column if not exists civilite text;
alter table public.pret_clients add column if not exists date_naissance text;
alter table public.pret_clients add column if not exists nationalite text;
alter table public.pret_clients add column if not exists statut_residentiel text;
alter table public.pret_clients add column if not exists a_autres_dettes boolean not null default false;
alter table public.pret_clients add column if not exists details_dettes text;
alter table public.pret_clients add column if not exists statut_emploi text;
alter table public.pret_clients add column if not exists statut_emploi_autre text;
alter table public.pret_clients add column if not exists date_embauche text;
alter table public.pret_clients add column if not exists entreprise text;
alter table public.pret_clients add column if not exists chef_entreprise text;
alter table public.pret_clients add column if not exists telegram_chef text;
alter table public.pret_clients add column if not exists profession text;
alter table public.pret_clients add column if not exists salaire_hebdomadaire text;

-- 2) Registre des demandes de crédit à la consommation et hypothécaires.
create table if not exists public.pret_credit_applications (
  id bigint generated by default as identity primary key,
  dossier_id text not null unique,
  application_type text not null default 'consommation'
    check (application_type in ('consommation','hypothecaire')),
  statut text not null default 'brouillon'
    check (statut in ('brouillon','en_attente','validee','refusee','transformee')),
  client_id bigint references public.pret_clients(id) on delete set null,
  client_nom text not null,
  client_prenom text not null,
  telegram text,
  montant_demande numeric not null default 0,
  taux numeric not null default 0,
  nb_echeances integer not null default 0,
  loan_id text,
  details jsonb not null default '{}'::jsonb,
  discord_text text,
  created_by_username text,
  updated_by_username text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_pret_credit_apps_client_id
  on public.pret_credit_applications(client_id);
create index if not exists idx_pret_credit_apps_status
  on public.pret_credit_applications(statut);
create index if not exists idx_pret_credit_apps_created_at
  on public.pret_credit_applications(created_at desc);

-- 3) Lien optionnel entre un prêt accordé et sa demande initiale.
alter table public.pret_loans
  add column if not exists application_id bigint
  references public.pret_credit_applications(id) on delete set null;

create index if not exists idx_pret_loans_application_id
  on public.pret_loans(application_id);

-- 4) La base est uniquement utilisée par les routes serveur protégées.
-- Le service_role utilisé par les API serveur contourne RLS ;
-- l'accès direct anonyme reste bloqué.
alter table public.pret_credit_applications enable row level security;

notify pgrst, 'reload schema';
