-- Banque Van Horn - Dossiers clients V3
-- Compatible avec pret_clients.id en BIGINT / int8.

DROP TABLE IF EXISTS public.pret_client_documents;
DROP TABLE IF EXISTS public.pret_client_notes;

CREATE TABLE public.pret_client_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES public.pret_clients(id) ON DELETE CASCADE,
  doc_type TEXT NOT NULL DEFAULT 'document',
  filename TEXT NOT NULL,
  storage_path TEXT NOT NULL,
  mime_type TEXT,
  size_bytes BIGINT,
  uploaded_by_username TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.pret_client_notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id BIGINT NOT NULL REFERENCES public.pret_clients(id) ON DELETE CASCADE,
  note TEXT NOT NULL,
  created_by_username TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ
);

CREATE INDEX idx_pret_client_documents_client_id
ON public.pret_client_documents(client_id);

CREATE INDEX idx_pret_client_documents_created_at
ON public.pret_client_documents(created_at DESC);

CREATE INDEX idx_pret_client_notes_client_id
ON public.pret_client_notes(client_id);

CREATE INDEX idx_pret_client_notes_created_at
ON public.pret_client_notes(created_at DESC);

-- Crée le bucket Storage si absent.
INSERT INTO storage.buckets (id, name, public)
VALUES ('client-documents', 'client-documents', false)
ON CONFLICT (id) DO NOTHING;

NOTIFY pgrst, 'reload schema';
