-- Banque Van Horn — Registre des rappels d'échéance
-- À exécuter une seule fois dans le projet Supabase « Banque Van Horn ».

create table if not exists public.pret_loan_reminders (
  id bigint generated by default as identity primary key,
  loan_id text not null,
  loan_reference text,
  client_name text,
  echeance_index integer not null check (echeance_index >= 0),
  echeance_date date,
  reminder_date date not null,
  reminder_time time without time zone,
  reminder_method text not null default 'telegram',
  note text,
  recorded_by_username text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_pret_loan_reminders_loan_echeance
  on public.pret_loan_reminders (loan_id, echeance_index);

create index if not exists idx_pret_loan_reminders_date
  on public.pret_loan_reminders (reminder_date desc, reminder_time desc);

alter table public.pret_loan_reminders enable row level security;

drop policy if exists "deny_anonymous_pret_loan_reminders" on public.pret_loan_reminders;
create policy "deny_anonymous_pret_loan_reminders"
  on public.pret_loan_reminders
  for all
  to anon
  using (false)
  with check (false);
