-- V12.6 - Suivi assurance-vie (migration additive et rejouable)
-- Ne modifie aucune table existante et ne contient aucun secret.

create table if not exists public.pret_life_insurance_contracts (
  id bigint generated by default as identity primary key,
  contract_number text not null unique,
  agency text not null check (agency in ('van_horn','saint_denis','rhodes','valentine')),
  subscriber_client_id bigint references public.pret_clients(id) on delete set null,
  subscriber_first_name text not null,
  subscriber_last_name text not null,
  subscriber_telegram text,
  beneficiary_first_name text not null,
  beneficiary_last_name text not null,
  beneficiary_telegram text,
  target_capital numeric(12,2) not null check (target_capital in (1000,2500,5000,7500,10000)),
  weekly_payment numeric(12,2) not null check (weekly_payment > 0),
  interest_rate_weekly numeric(7,4) not null default 0.05 check (interest_rate_weekly = 0.05),
  start_date date not null,
  status text not null default 'active' check (status in (
    'active','payments_complete','placed','closure_requested','closed',
    'death_reported','under_review','paid_to_beneficiary'
  )),
  payments jsonb not null default '[]'::jsonb check (jsonb_typeof(payments) = 'array'),
  closure_fee numeric(12,2),
  closure_net_amount numeric(12,2),
  closed_at timestamptz,
  death_reported_at timestamptz,
  beneficiary_paid_at timestamptz,
  notes text,
  created_by_id bigint,
  created_by_username text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.pret_life_insurance_events (
  id bigint generated by default as identity primary key,
  contract_id bigint not null references public.pret_life_insurance_contracts(id) on delete cascade,
  event_type text not null,
  actor_username text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists pret_life_insurance_contracts_status_idx
  on public.pret_life_insurance_contracts(status);
create index if not exists pret_life_insurance_contracts_agency_idx
  on public.pret_life_insurance_contracts(agency);
create index if not exists pret_life_insurance_events_contract_idx
  on public.pret_life_insurance_events(contract_id, created_at desc);

alter table public.pret_life_insurance_contracts enable row level security;
alter table public.pret_life_insurance_events enable row level security;

comment on table public.pret_life_insurance_contracts is
  'Suivi des contrats assurance-vie : 8 versements hebdomadaires, intérêts hebdomadaires de 5 %, bénéficiaire unique.';
comment on column public.pret_life_insurance_contracts.beneficiary_first_name is
  'Immuable après création : tout changement exige un nouveau contrat signé.';
comment on column public.pret_life_insurance_contracts.payments is
  'Huit échéances hebdomadaires identiques avec date, montant, statut et date de paiement.';
