-- V12.3.1 — Carnet d'adresses des télégrammes
create table if not exists public.pret_telegram_contacts (
  id bigint generated by default as identity primary key,
  client_id bigint null references public.pret_clients(id) on delete set null,
  prenom text not null default '',
  nom text not null default '',
  telegram text not null default '',
  telegram_normalized text not null default '',
  fonction text not null default '',
  agence text null,
  source text not null default 'manuel',
  discord_message_id text null,
  created_by text null,
  updated_by text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists pret_telegram_contacts_client_unique
  on public.pret_telegram_contacts(client_id)
  where client_id is not null;

create unique index if not exists pret_telegram_contacts_telegram_unique
  on public.pret_telegram_contacts(telegram_normalized)
  where telegram_normalized <> '';

create index if not exists pret_telegram_contacts_nom_idx
  on public.pret_telegram_contacts(lower(nom), lower(prenom));
